# Generated by Django 4.1.6 on 2023-02-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
            ],
        ),
    ]
